name: reunirts
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  url_strategy: ^0.2.0
  get: ^4.6.5
  simple_gradient_text: ^1.3.0
  dropdown_button2: ^2.3.9
  fading_edge_scrollview: ^4.1.1
  intl: ^0.19.0
  pinput: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets: 
    - res/images/
    - res/fonts/
    - res/icons/

  fonts:    
    - family: Montserrat
      fonts:
        - asset: res/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: res/fonts/Montserrat-Bold.ttf
          weight: 800
    - family: Metropolis
      fonts:
        - asset: res/fonts/Metropolis-Black.ttf
          weight: 900
        - asset: res/fonts/Metropolis-ExtraBold.ttf
          weight: 800
        - asset: res/fonts/Metropolis-Bold.ttf
          weight: 700
        - asset: res/fonts/Metropolis-SemiBold.ttf
          weight: 600
        - asset: res/fonts/Metropolis-Medium.ttf
          weight: 500
        - asset: res/fonts/Metropolis-Regular.ttf
          weight: 400